### PART A:::

-- 1.	Read the data from all tables.

-- 2.	Find the country wise count of customers.

-- 3.	Display the products which are not discontinued.

-- 4.	Display the list of companies along with the product name that they are supplying.

-- 5.	Display customer's information who stays in 'Mexico'

-- 6.	Display the price of costliest item that is ordered by the customer along with the customer details.

-- 7.	Display supplier id who owns highest number of products.

-- 8.	Display month wise and year wise count of the orders placed.

-- 9.	Which country has maximum suppliers.

-- 10. Which customers did not place any order.


### PART B:::

-- 1.	Arrange the product id, product name based on high demand by the customer.

-- 2.	Display the number of orders delivered every year.

-- 3.	Calculate year-wise total revenue.

-- 4.	Display the customer details whose order amount is maximum including his past orders.

-- 5.	Display total amount ordered by each customer from high to low. (donot use sum)

/* A sales and marketing department of this company wants to find out how frequently 
customer have business with them. This can be done in two ways. (Answer Q 6 and Q 7 for the same) */
-- 6 Approach 1. List the current and previous order amount for each customers.

/* 7. Approach 2. Display the customerid, order ids and the 
order dates along with the previous order date and the next order date for every customer in the table:: */


-- 8.	Find out top 3 suppliers in terms of revenue generated by their products.







